[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && npm install --include=dev",
  "cd backend && npm install --include=dev"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "node backend/src/migrate.js && node backend/src/server.js"
